name: PUBG News

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15min执行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  pubg-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          BARK_PUSH_URL: ${{ secrets.BARK_PUSH_URL }}
        run: python pubg_news.py

      - name: Commit updated news files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

          git pull --rebase --autostash

          git add news_*.json

          if git diff --cached --quiet; then
            echo "✅ No news updates to commit."
          else
            git commit -m "Update news"
            git push
          fi
